---
title: "Reaction to the Census Bureau's Updated Parameters"
description: |
    The Data Stewardship Executive Policy Committee announces a higher privacy 
    loss budget and other changes to the Disclosure Avoidance System.
preview: census_slide.jpg
author:
    - name: Christopher T. Kenny
      affiliation: Department of Government, Harvard University
      location: Cambridge, MA
      email: christopherkenny@fas.harvard.edu
    - name: Shiro Kuriwaki
      affiliation: Department of Government, Harvard University
      location: Cambridge, MA
      email: kuriwaki@g.harvard.edu
    - name: Cory McCartan
      affiliation: Department of Statistics, Harvard University
      location: Cambridge, MA
      email: cmccartan@fas.harvard.edu
    - name: Evan Rosenman
      affiliation: Harvard Data Science Initiative
      location: Cambridge, MA
      email: erosenm@fas.harvard.edu
    - name: Tyler Simko
      affiliation: Department of Government, Harvard University
      location: Cambridge, MA
      email: tsimko@g.harvard.edu
    - name: Kosuke Imai
      affiliation: Departments of Government and Statistics, Harvard University
      location: Cambridge, MA
      email: imai@harvard.edu
date: June 9, 2021
citation: false
---

On June 9, The Census Bureau released [information on their final 
parameters](https://www.census.gov/newsroom/press-releases/2021/2020-census-key-parameters.html)
for the 2020 Census data release. We are grateful that they have incorporated
some of the recommendations [from our report](https://arxiv.org/abs/2105.14197)
to help build a better data product for redistricting.

The Bureau has made several welcome changes. They state that they have updated
the post-processing component of the Disclosure Avoidance System (DAS) to
address the undercounting bias in racially and ethnically diverse areas, which
we reported in our analysis. As we recommended, the Bureau has also increased
the privacy-loss budget, allocating the increase towards more accurate
population and racial counts on geographies at the block group level and higher.
We are hopeful that this targeted increase will help attenuate the DAS- induced
population change at the voting district and precinct level.

Some unresolved issues remain, however. The Bureau indicates that a new
demonstration data product will not be released until September. Yet they plan
to first release 2020 census redistricting data, which we expect states and
localities to begin using immediately, by [August 16,
2021](https://www.census.gov/newsroom/press-releases/2021/2020-census-apportionment-results.html).[^1]
Given the timing, it is unclear how the evaluation of the new demonstration data
will affect the upcoming redistricting process and related litigation.  The
Bureau also states that there will be no direct increases in accuracy for
block-level data, in order to protect privacy.  As this is a key aspect of
ensuring the equality of vote and protecting the principle of One Person, One
Vote, map drawers and analysts may have to adjust their interpretation of this
long-standing principle.

[^1]: Caliper, who makes the software Maptitude for Redistricting, [has
    announced they will process the legacy format
    data](https://www.caliper.com/learning-redistricting/index.php/articles/when-will-i-receive-my-2020-redistricting-data/),
    and two ALARM Project members have created [an R package to process legacy
    data](https://corymccartan.github.io/PL94171/) as well. These types of
    resources should allow people to immediately begin drawing maps.

The Bureau also announced that they plan to release the final version of the DAS
code base.  This is an important step for transparency. However, the code alone
does not allow analysts to evaluate the impacts of DAS on redistricting and
properly account for the additional uncertainty due to the injected noise. We
recommend the Bureau also release differentially private noisy population counts
that have not been subject to the post-processing steps, as well as parameter
values used for noise generation. Although scholarly communities have not fully
resolved the issue of incorporating additional noise into redistricting
simulation analysis, the availability of such information should facilitate
future methodological development. In particular, it is of interest to examine
whether or not the additional noise makes it more difficult to detect partisan
and racial gerrymandering.

