---
title: Posts
site: distill::distill_website
listing: posts
---

<div class="home-cover l-screen">
<div class="fg">
<h1>Developing methodology and tools to analyze legislative redistricting.</h1>
</div>
</div>

The ALARM Project is a research team at Harvard University led by 
[Kosuke Imai](https://imai.fas.harvard.edu/).  It conducts research into
redistricting sampling algorithms, best practices and workflows for
redistricting analysis, and tools to visualize, explore, and understand
redistricting plans.

<div class="package-box">
<a href="https://alarm-redist.github.io/redist/">
<h2><code>redist</code>: Simulation Methods for Legislative Redistricting</h2>
</a>
<p>
Enables researchers to sample redistricting plans from a pre-specified target
distribution using state-of-the-art algorithms. Implements a wide variety
constraints in the redistricting process, such as geographic compactness and
population parity requirements. Tools for analysis such as computation of
various summary statistics and plotting functionality are also included.
</p>
<p>
<a href="https://alarm-redist.github.io/redist/">
Go to package home page &raquo;
</a>
</p>
</div>

