---
title: "Widespread Partisan Gerrymandering Mostly Cancels Nationally, but Reduces Electoral Competition Published in PNAS"
description: |
  Our paper which details gerrymandering and partisan fairness in the 2022 redistricting maps is now published in PNAS.
author:
  - name: Christopher T. Kenny
    url: https://www.christophertkenny.com/
  - name: Cory McCartan
    url: https://www.corymccartan.com
  - name: Tyler Simko
    url: https://tylersimko.com/
  - name: Shiro Kuriwaki
    url: https://www.shirokuriwaki.com/
  - name: Kosuke Imai
    url: https://imai.fas.harvard.edu/
date: 2023-06-13
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Today, our paper [*Widespread Partisan Gerrymandering Mostly Cancels Nationally, but Reduces Electoral Competition* was published in PNAS](TODO link once available). 

We evaluate partisan gerrymandering nationwide for new 2020 districts using simulated maps that account for geography and state-specific rules. We find evidence that gerrymandering is widespread across states, resulting in disadvantages for the Democratic party and less competitive districts. Read the abstract below:

> Redistricting plans in legislatures determine how voters' preferences are translated into representative's seats. Political parties may manipulate the redistricting process to gain additional seats and insulate incumbents from electoral competition, a process known as *gerrymandering*. But detecting gerrymandering is difficult without a representative set of alternative plans that comply with the same geographic and legal constraints. Harnessing recent algorithmic advances in sampling, we study such a collection of alternative redistricting plans that can serve as a non-partisan baseline. This methodological approach can distinguish electoral bias due to partisan effects from electoral bias due to other factors. We find that Democrats are structurally and geographically disadvantaged in House elections by 8 seats, while partisan gerrymandering disadvantages them by 2 seats.

If you're interested in further details on this research project, take a look at the [Supplementary Information](TODO link once available) or our [replication data](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/JI1U8X).

This research would not be possible without the [50-State Redistricting Simulations](https://alarm-redist.org/fifty-states/). A special thank you to George Garcia, Kevin Wang, and Melissa Wu.


