---
title: "Letter: Researchers need better access to US Census data published in Science"
description: |
  Our letter providing recommendations to the Census Bureau about the Noisy Measurements File (NMF) now published in Science.
author:
  - name: Cory McCartan
    url: https://www.corymccartan.com
  - name: Tyler Simko
    url: https://tylersimko.com/
  - name: Kosuke Imai
    url: https://imai.fas.harvard.edu/
date: 2023-06-03
---

For the 2020 decennial census, the Census Bureau adopted a new Disclosure Avoidance System (DAS) based on differential privacy.
The DAS was designed to protect the confidentiality of responses by injecting statistical noise into a confidential individual census dataset.
A key output of this system is the Noisy Measurement File (NMF), which is produced by adding random noise to tabulated statistics.
The resulting Noisy Measurement File (NMF) is an invaluable resource for Census data users to understand the error introduced by the DAS and perform statistically valid analyses that properly account for DAS-introduced error.

The Bureau did not initially release the NMF, but released a demonstration version in April 2023 after several public requests and subsequent litigation. The Bureau plans to release the NMF for the P.L.94-171 redistricting data and more detailed census data (the DHC file) later this year.

We commend the Bureau's decision to provide the NMF, which will help advance social science research, improve policy decisions, and further strengthen the DAS itself.
To maximize the benefits of the released NMF, however, we believe that the Bureau must substantially improve the way in which the NMF is formatted and released.
In a [letter](https://www.science.org/doi/10.1126/science.adi7004) recently published in *Science*, we explain several obstacles researchers may face when accessing, processing, and using the demonstration data for statistical analyses. We include several recommendations for the Bureau for future NMF releases.
Our [longer version of this letter](https://arxiv.org/pdf/2305.07208.pdf) describes how researchers can transform the NMF into a usable format and includes more detailed recommendations.
