<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sho Miyazaki, Kevin Wang, Melissa Wu, Kento Yamada">

<title>redist 101 – ALARM Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./assets/alarm_256_tr.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-64517d29a6ba58f883cb4fedc2dde26a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-8ZZ8YY5N8M"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-8ZZ8YY5N8M', { 'anonymize_ip': true});
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./assets/alarm_256_tr.png" alt="" class="navbar-logo light-content">
    <img src="./assets/alarm_256_tr.png" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">ALARM Project</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./applications.html"> 
<span class="menu-text">Reports and Publications</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://alarm-redist.github.io/redist/"> 
<span class="menu-text">redist</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/alarm-redist"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/alarm_redist"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">redist 101</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sho Miyazaki, Kevin Wang, Melissa Wu, Kento Yamada </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<p><br> <em>“There are a handful of college professors who even have the expertise to run [redistricting] simulations in the first place.”</em> <br></p>
<div data-align="right">
<p>—lawyer from oral arguments before the Supreme Court in <a href="https://www.scotusblog.com/case-files/cases/merrill-v-milligan-2/"><em>Merrill v. Milligan</em></a></p>
</div>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="https://alarm-redist.org/fifty-states/AL_cd_2020/index_files/figure-html/enacted-samples-1.svg" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This vignette introduces algorithmic redistricting analysis using the <code>redist</code> package. It also demonstrates the <code>alarmdata</code> package, which downloads ready-to-use redistricting data and simulations from the ALARM Project’s <a href="https://alarm-redist.org/fifty-states/">50-State Redistricting Simulations</a>.</p>
<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<section id="why-simulate" class="level3">
<h3 class="anchored" data-anchor-id="why-simulate">Why Simulate?</h3>
<p>When attempting to detect gerrymandering, we want to determine whether a certain district map is unfair. But what makes a map unfair, and how do we identify whether a map is unfair? The problem is that it is not obvious what standard to which we should compare an existing map.</p>
<p>The key challenge is constructing a counterfactual. We want to compare an existing map to a set of alternative redistricting plans that are drawn following the same rules as those used in the actual redistricting process.</p>
<p>One potential solution is to list all possible plans. Unfortunately, this is impossible in most cases because the number of potential plans tends to be astronomically large. Even under a simple scenario in which an 8-by-8 checkerboard is split into two contiguous districts, the number of unique plans totals over <span class="math inline">\(1.2 \times 10^{11}\)</span> (Fifield et al., 2020). In real-world redistricting problems, we often deal with thousands of administrative units. Thus, enumerating all potential plans is unrealistic.</p>
<p>Another idea might be to compare the plan under question to plans adopted in other states, or to plans that were used in the same state in the past. This is, again, is a misleading approach because the geographical distributions of voters differ across different states and different time periods. Moreover, each state follows its own rules for redistricting, and we cannot justify comparing plans that were drawn under different rules (Kenny et al., 2022).</p>
<p>Therefore, we would want to sample plans that follow the same rules used in the real redistricting process and that are based on the real distribution of voters in the same state, in the same time period.</p>
<p>Simulations make this possible. Using simulations, we can obtain a representative sample of redistricting plans that follow the constraints that are used in the actual redistricting process such as:</p>
<ul>
<li>Contiguity (Making sure that districts are contiguous)</li>
<li>Population parity (Making sure that districts have equal population)</li>
<li>Limiting administrative boundary splits</li>
<li>Other idiosyncratic requirements, such as connecting counties by transportation links</li>
</ul>
<p>Typically, we draw a few thousand plans in each state, making sure that the plans are unique and that the sample is representative. Then, we compare the simulated plans with the enacted/proposed map to see whether, for example, the map under question disproportionately favors one group over another. For a more intuitive explanation of simulations, check out this Washington Post article titled <a href="https://www.washingtonpost.com/politics/interactive/2022/algorithmic-redistricting/">“Can computer simulations help fix democracy?”</a>. The article talks about how Prof.&nbsp;Kosuke Imai, head of the ALARM Project, served as an expert witness in a redistricting litigation in Ohio.</p>
</section>
<section id="evaluating-plans" class="level3">
<h3 class="anchored" data-anchor-id="evaluating-plans">Evaluating Plans</h3>
<p>After we obtain a representative sample of redistricting plans, we can detect whether the map under question was gerrymandered by comparing the map with the simulated plans. <code>redist</code> and its associated packages are equipped with tools that allow you to conduct and visualize such analysis. The metrics used in such analysis include:</p>
<ul>
<li>The number of seats that each party is expected to win under the enacted/proposed plan and the simulated plans</li>
<li>The two-party vote margin in each district, which is useful when trying to identify whether specific groups of voters have been packed into a small number of districts or splintered into numerous districts</li>
<li>The efficiency gap, which represents the degree to which the votes cast for each party are wasted</li>
<li>The partisan bias of plans, which quantifies the excess seat share per party relative to the party’s vote share</li>
</ul>
<p>We can conclude that there is evidence of gerrymandering if the map under question is a clear outlier relative to the simulated plans. Check out how we conduct these types of analysis in our <a href="https://alarm-redist.org/fifty-states/about/">50-State Simulation Project</a>.</p>
</section>
<section id="references-and-further-reading" class="level3">
<h3 class="anchored" data-anchor-id="references-and-further-reading">References and Further Reading</h3>
<p>Fifield, B., Imai, K., Kawahara, J., &amp; Kenny, C. T. (2020). The Essential Role of Empirical Validation in Legislative Redistricting Simulation. <em>Statistics and Public Policy, 7</em>(1), 52–68. <a href="https://doi.org/10.1080/2330443X.2020.1791773" class="uri">https://doi.org/10.1080/2330443X.2020.1791773</a></p>
<p>Kenny, C. T., McCartan, C., Simko, T., Kuriwaki, S., &amp; Imai, K. (2022). Widespread Partisan Gerrymandering Mostly Cancels Nationally, but Reduces Electoral Competition. <a href="https://doi.org/10.48550/ARXIV.2208.06968" class="uri">https://doi.org/10.48550/ARXIV.2208.06968</a></p>
</section>
</section>
<section id="redistricting-simulation-workflow" class="level2">
<h2 class="anchored" data-anchor-id="redistricting-simulation-workflow">Redistricting Simulation Workflow</h2>
<p>Before starting, we need to load the following packages, which contain the functions necessary to conduct the simulations.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alarmdata)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(redist)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="building-data-objects" class="level2">
<h2 class="anchored" data-anchor-id="building-data-objects">Building Data Objects</h2>
<section id="redist_map" class="level3">
<h3 class="anchored" data-anchor-id="redist_map"><code>redist_map</code></h3>
<p>The first step in a <code>redist</code> analysis is to create the <code>redist_map</code> object, which stores the basic parameters of the redistricting problem. Here, we use <code>redist_map</code> objects that can be downloaded from the <a href="https://alarm-redist.org/fifty-states/">50-State Redistricting Simulations</a> using the <code>alarmdata</code> package.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>map_nc <span class="ot">&lt;-</span> <span class="fu">alarm_50state_map</span>(<span class="st">"NC"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(map_nc)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>To be partitioned into 14 districts with population between 745,670.6 - 0.5% and 745,670.6 + 0.5%
With geometry:
    bbox:           xmin: 124003.2 ymin: 821.8034 xmax: 935804 ymax: 318096.6
    projected CRS:  NAD83(HARN) / North Carolina
# A tibble: 2,666 × 59
   GEOID   state county muni  county_muni cd_2010 vtd     pop pop_hisp pop_white
 * &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;         &lt;int&gt; &lt;chr&gt; &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
 1 370010… NC    Alama… &lt;NA&gt;  Alamance C…       6 0000…  5135      251      4420
 2 370010… NC    Alama… &lt;NA&gt;  Alamance C…       6 0000…  4771      190      4225
 3 370010… NC    Alama… &lt;NA&gt;  Alamance C…       6 0000…  5427      231      4536
 4 370010… NC    Alama… &lt;NA&gt;  Alamance C…       6 0000…  3399      179      2926
 5 370010… NC    Alama… &lt;NA&gt;  Alamance C…       6 0000…  4456      318      3675
 6 370010… NC    Alama… &lt;NA&gt;  Alamance C…       6 0000…  4741      521      2491
 7 370010… NC    Alama… &lt;NA&gt;  Alamance C…       6 0000…  6190     1506      2655
 8 370010… NC    Alama… 21095 Alamance C…       6 0000…  8320      596      6321
 9 370010… NC    Alama… 09060 Alamance C…       6 0000…  2755      161      2256
10 370010… NC    Alama… 21095 Alamance C…       6 0000…  5578      262      4539
# ℹ 2,656 more rows
# ℹ 49 more variables: pop_black &lt;dbl&gt;, pop_aian &lt;dbl&gt;, pop_asian &lt;dbl&gt;,
#   pop_nhpi &lt;dbl&gt;, pop_other &lt;dbl&gt;, pop_two &lt;dbl&gt;, vap &lt;dbl&gt;, vap_hisp &lt;dbl&gt;,
#   vap_white &lt;dbl&gt;, vap_black &lt;dbl&gt;, vap_aian &lt;dbl&gt;, vap_asian &lt;dbl&gt;,
#   vap_nhpi &lt;dbl&gt;, vap_other &lt;dbl&gt;, vap_two &lt;dbl&gt;, pre_16_rep_tru &lt;dbl&gt;,
#   pre_16_dem_cli &lt;dbl&gt;, uss_16_rep_bur &lt;dbl&gt;, uss_16_dem_ros &lt;dbl&gt;,
#   gov_16_rep_mcc &lt;dbl&gt;, gov_16_dem_coo &lt;dbl&gt;, atg_16_rep_new &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>As shown above, <code>redist_map</code> (and shapefiles) looks like a dataframe with many columns, such as population and geographical information.</p>
<p>For example, the <code>geometry</code> column contains the geographic shapefile information, which can be mapped as a <code>POLYGON</code> (or <code>MULTIPOLYGON</code>) shape of the geographical area.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(map_nc<span class="sc">$</span>geometry)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Geometry set for 6 features 
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 560601.5 ymin: 232341.7 xmax: 586454.5 ymax: 277431.7
Projected CRS: NAD83(HARN) / North Carolina
First 5 geometries:</code></pre>
</div>
</div>
</section>
<section id="shapefiles-and-projections" class="level3">
<h3 class="anchored" data-anchor-id="shapefiles-and-projections">Shapefiles and Projections</h3>
<p>If you want to use the other shapefile data for the redistricting analysis (other countries, etc.), you need to transform the available shapefiles (census data, etc.) into a <code>redist_map</code> object.</p>
<p>As there are multiple formats of <a href="https://r-spatial.github.io/sf/">shapefiles</a>, you may also need to convert and adjust them into a unified format. For example, projections must be in the same style. For more information, check pp.17-18 of <a href="https://docs.google.com/presentation/d/1FlTfDv8sjhDxxU2KIOnKd1SHhvivm7WdD0bYdrNNgo0/edit#slide=id.g11d65f9e588_0_0">this presentation for the workshop</a>.</p>
</section>
<section id="adjacency-list" class="level3">
<h3 class="anchored" data-anchor-id="adjacency-list">Adjacency List</h3>
<p>Since districts are generally required to be contiguous, all <code>redist</code> algorithms require an <em>adjacency graph</em>, which is constructed from the geography of the actual precincts (or other redistricting unit).</p>
<p>What is adjacency? It is the formalization of contiguity. Two units are adjacent if they are contiguous geographically.</p>
<p>Let’s check what the adjacency list looks like. The <code>adj</code> column of <code>redist_map</code> is the adjacency list.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(map_nc<span class="sc">$</span>adj)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1]    1    4   18   19  423  997 1994

[[2]]
[1]    0    4   10   13   30  997 1107

[[3]]
[1]    3    7   28  380 1157 1159 2074

[[4]]
[1]   2   5   6  12  28 375 380

[[5]]
[1]  0  1 13 16 18 20 21

[[6]]
[1]    3    6   23  374  375 1842</code></pre>
</div>
</div>
<p>As you can see, the adjacency list of each precinct contains all other precincts to which it is adjacent/with which it is contiguous.</p>
<p>Using the <code>redist_map</code> object, we can plot this adjacency list.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(map_nc, <span class="at">adj =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="redist101_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>You may need to fix the adjacency list manually with the <a href="https://christophertkenny.com/geomander/reference/add_edge.html"><code>geomander</code> package</a>, particularly when there are bodies of water or islands connected by bridges.</p>
</section>
<section id="further-pre-processing" class="level3">
<h3 class="anchored" data-anchor-id="further-pre-processing">Further Pre-Processing</h3>
<p>Often, we want to only analyze a portion of a map, or hold some districts fixed while others are re-simulated. We may also want to implement a status-quo-type constraint that encourages simulated districts to be close to a reference plan. This can be accomplished by freezing the “cores” of each district.</p>
<p>All of these operations fall under the umbrella of map pre-processing, and <code>redist</code> is well-equipped to handle them.</p>
<p>The map <a href="https://alarm-redist.org/redist/articles/map-preproc.html">pre-processing vignette</a> contains more information and examples about these operations.</p>
</section>
</section>
<section id="simulating-redistricting-plans" class="level2">
<h2 class="anchored" data-anchor-id="simulating-redistricting-plans">Simulating redistricting plans</h2>
<section id="sampling-algorithms" class="level3">
<h3 class="anchored" data-anchor-id="sampling-algorithms">Sampling Algorithms</h3>
<p>As discussed above, we want to create counterfactual plans by obtaining a representative sample with simulation algorithms. The <code>redist</code> package has three functions that use Sequential Monte Simulations (<code>redist_smc</code>) and Markov Chain Monte Carlo (<code>redist_flip</code> and <code>redist_mergesplit</code>) algorithms. In this section, we will pick up <code>redist_smc</code>, which generates nearly independent congressional or legislative redistricting plans according to contiguity, population, compactness, and administrative boundary constraints. For the details of the functions, check the following.</p>
<ul>
<li><a href="https://alarm-redist.org/redist/reference/redist_smc.html"><code>redist_smc</code></a></li>
<li><a href="https://alarm-redist.org/redist/reference/redist_flip.html"><code>redist_flip</code></a> and *<a href="https://alarm-redist.org/redist/reference/redist_mergesplit.html"><code>redist_mergesplit</code></a></li>
</ul>
</section>
<section id="redist_smc" class="level3">
<h3 class="anchored" data-anchor-id="redist_smc"><code>redist_smc</code></h3>
<p>Once the <code>redist_map</code> is ready, we can run the simple simulations. Here, let’s try generating five hundred simulated plans for North Carolina. Note that we can ask <code>redist_smc</code> to produce five hundred plans by combining two separate simulation runs. This ensures that the algorithm “converges”–that is, that the distribution of plans we obtain is stable.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>smc_plans_basic <span class="ot">&lt;-</span> <span class="fu">redist_smc</span>(map_nc, <span class="at">nsims =</span> <span class="dv">500</span>, <span class="at">runs =</span> <span class="dv">4</span>L) <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">plan_dev =</span> <span class="fu">plan_parity</span>(map_nc),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">comp_edge =</span> <span class="fu">distr_compactness</span>(map_nc),</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">county_splits =</span> <span class="fu">county_splits</span>(map_nc, map_nc<span class="sc">$</span>county),</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">e_dvs =</span> <span class="fu">partisan_metrics</span>(map_nc, <span class="st">"DVS"</span>, nrv, ndv)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now, you have got 2,000 plans. The output of the simulations is <code>redist_plans</code> format. The followings are the first six plans generated by the simulations, and you can plot them.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">redist.plot.plans</span>(smc_plans_basic, <span class="at">draws =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">shp =</span> map_nc)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="redist101_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Using the <code>summary</code> function, we can perform a diagnostic check to ensure that our plans have converged and are diverse (in other words, that we are exploring a sufficient space of possible alternative plans, rather than simulating the same plan over and over again).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(smc_plans_basic)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
R-hat values for summary statistics:
     plan_dev     comp_edge county_splits         e_dvs 
        1.032       ❌1.056         1.031       ❌1.104 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>         Eff. samples (%) Acc. rate Log wgt. sd  Max. unique Est. k 
Split 1       463 (92.5%)     22.1%        0.52   311 ( 98%)      6 
Split 2       468 (93.5%)     31.7%        0.50   314 ( 99%)      4 
Split 3       470 (94.0%)     26.9%        0.48   328 (104%)      4 
Split 4       467 (93.4%)     30.0%        0.50   308 ( 97%)      3 
Split 5       466 (93.1%)     36.8%        0.51   315 (100%)      2 
Split 6       449 (89.9%)     25.6%        0.58   314 ( 99%)      3 
Split 7       426 (85.3%)     23.8%        0.64   307 ( 97%)      3 
Split 8       406 (81.2%)     28.8%        0.77   294 ( 93%)      2 
Split 9       420 (84.0%)     26.9%        0.76   314 ( 99%)      2 
Split 10      435 (87.0%)     16.3%        0.72   305 ( 97%)      3 
Split 11      423 (84.5%)     19.9%        0.75   294 ( 93%)      2 
Split 12      431 (86.2%)     11.5%        0.75   283 ( 90%)      3 
Split 13      442 (88.3%)      6.1%        0.68   259 ( 82%)      2 
Resample      299 (59.7%)       NA%        0.68   362 (115%)     NA </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>         Eff. samples (%) Acc. rate Log wgt. sd  Max. unique Est. k 
Split 1       465 (92.9%)     22.0%        0.51   313 ( 99%)      6 
Split 2       469 (93.7%)     23.5%        0.50   318 (101%)      5 
Split 3       463 (92.7%)     26.9%        0.53   300 ( 95%)      4 
Split 4       466 (93.2%)     30.9%        0.51   310 ( 98%)      3 
Split 5       434 (86.8%)     29.4%        0.61   322 (102%)      3 
Split 6       441 (88.2%)     25.9%        0.64   289 ( 91%)      3 
Split 7       452 (90.4%)     30.8%        0.59   303 ( 96%)      2 
Split 8       403 (80.7%)     30.8%        0.67   299 ( 95%)      2 
Split 9       382 (76.4%)     28.6%        0.77   308 ( 97%)      2 
Split 10      428 (85.6%)     18.3%        0.74   289 ( 91%)      3 
Split 11      330 (66.0%)     20.1%        0.79   284 ( 90%)      2 
Split 12      335 (67.1%)     13.2%        0.86   275 ( 87%)      2 
Split 13      434 (86.7%)      4.5%        0.70   267 ( 84%)      2 
Resample      263 (52.6%)       NA%        0.70   352 (111%)     NA </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>         Eff. samples (%) Acc. rate Log wgt. sd  Max. unique Est. k 
Split 1       463 (92.6%)     17.6%        0.52   318 (101%)      8 
Split 2       468 (93.6%)     23.1%        0.51   308 ( 97%)      5 
Split 3       468 (93.5%)     26.3%        0.50   310 ( 98%)      4 
Split 4       463 (92.5%)     31.2%        0.53   305 ( 97%)      3 
Split 5       450 (90.0%)     29.4%        0.57   310 ( 98%)      3 
Split 6       454 (90.8%)     15.4%        0.59   304 ( 96%)      5 
Split 7       440 (88.1%)     19.1%        0.63   315 (100%)      4 
Split 8       442 (88.3%)     21.1%        0.65   314 ( 99%)      3 
Split 9       444 (88.8%)     26.1%        0.65   308 ( 97%)      2 
Split 10      426 (85.2%)     22.5%        0.71   282 ( 89%)      2 
Split 11      433 (86.5%)     13.8%        0.72   290 ( 92%)      3 
Split 12      443 (88.7%)     15.1%        0.66   289 ( 91%)      2 
Split 13      445 (89.0%)      5.1%        0.65   261 ( 83%)      2 
Resample      290 (58.0%)       NA%        0.65   367 (116%)     NA </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>         Eff. samples (%) Acc. rate Log wgt. sd  Max. unique Est. k 
Split 1       466 (93.1%)     16.0%        0.50   331 (105%)      8 
Split 2       466 (93.3%)     23.0%        0.50   316 (100%)      5 
Split 3       468 (93.6%)     21.6%        0.49   325 (103%)      5 
Split 4       464 (92.9%)     31.2%        0.51   320 (101%)      3 
Split 5       462 (92.3%)     27.4%        0.52   308 ( 97%)      3 
Split 6       460 (92.0%)     26.2%        0.57   318 (101%)      3 
Split 7       437 (87.4%)     18.3%        0.66   305 ( 97%)      4 
Split 8       445 (89.0%)     17.0%        0.64   302 ( 96%)      4 
Split 9       432 (86.5%)     20.0%        0.68   293 ( 93%)      3 
Split 10      434 (86.7%)     24.5%        0.72   290 ( 92%)      2 
Split 11      445 (88.9%)     13.2%        0.67   286 ( 90%)      3 
Split 12      431 (86.1%)     15.5%        0.71   285 ( 90%)      2 
Split 13      434 (86.8%)      5.7%        0.69   256 ( 81%)      2 
Resample      241 (48.3%)       NA%        0.69   361 (114%)     NA </code></pre>
</div>
</div>
</section>
<section id="constraints" class="level3">
<h3 class="anchored" data-anchor-id="constraints">Constraints</h3>
<p>The simulation output from the SMC is unbiased random sample, but not always mean representative. Since each state (or equivalent) has a different legal requirements for the redistricting plan, representative sample has to be in the resemble the space of legal possibilities. Thus, we need to customize the constraints to operationalize legal requirements and norms. For example, in some cases, each district has to have an equal population, while the margins of tolerance exist, which can be varied by the state. To adjust to that rule, we can customize the constraints as you can see below. In <code>redist</code>, you can add both <em>hard</em> and <em>soft</em> constraints.</p>
<section id="hard-constraints" class="level4">
<h4 class="anchored" data-anchor-id="hard-constraints">Hard Constraints</h4>
<ul>
<li>Population Tolerance (<code>pop_tol</code>= 0.0x) – all plans must be within x% of population equality.</li>
<li>Contiguity – all plans must be contiguous</li>
<li>County splits – all plans must have up to a small number of splits</li>
</ul>
</section>
<section id="soft-constraints" class="level4">
<h4 class="anchored" data-anchor-id="soft-constraints">Soft Constraints</h4>
<ul>
<li><code>redist</code> allows you to add soft constraints that are listed <a href="https://alarm-redist.org/redist/reference/constraints.html">here</a></li>
<li>Using <a href="https://alarm-redist.org/redist/reference/constraints.html"><code>add_constr_xyz()</code></a> (<code>xyz</code> varies depending on the constraints you want to add) functions, you can add constraints on the redistricting process to be encoded in the target distribution for sampling of <code>redist_smc()</code> and <code>redist_mergesplit()</code></li>
<li>Note that higher and higher strength values will eventually cause the algorithm’s accuracy and efficiency to suffer, so be sure to check all sampling diagnostics.</li>
</ul>
</section>
</section>
<section id="example" class="level3">
<h3 class="anchored" data-anchor-id="example">Example</h3>
<section id="change-population-tolerance" class="level4">
<h4 class="anchored" data-anchor-id="change-population-tolerance">Change Population Tolerance</h4>
<p>You can use <code>get_pop_tol()</code> function to check the current population tolerance of <code>redist_map</code> object.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_pop_tol</span>(map_nc)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.005</code></pre>
</div>
</div>
<p>As you can see above, the population tolerance of <code>map_nc</code> is 0.005. This means that all plans must be within 0.5% of population equality. This is why you can see the output message of <code>redist_smc()</code> shows following.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">redist_smc</span>(map_nc, <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>SEQUENTIAL MONTE CARLO
Sampling 10 2666-unit maps with 14 districts and population between 741942 and 749399.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>With plans resampled from weights
Plans matrix: int [1:2666, 1:11] 1 1 1 1 1 1 1 1 1 1 ...
# A tibble: 154 × 3
   draw    district total_pop
   &lt;fct&gt;      &lt;int&gt;     &lt;dbl&gt;
 1 cd_2020        1    745033
 2 cd_2020        2    744646
 3 cd_2020        3    747128
 4 cd_2020        4    745889
 5 cd_2020        5    745852
 6 cd_2020        6    745599
 7 cd_2020        7    746762
 8 cd_2020        8    745420
 9 cd_2020        9    747640
10 cd_2020       10    746272
# ℹ 144 more rows</code></pre>
</div>
</div>
<p>As you can see, all the <code>total_pop</code> should be within between 741,942 and 749,399, which is 0.5% of population equality.</p>
<p>Then, let’s change the population tolerance with <code>set_pop_tol()</code> function. Here, we will set <code>pop_tol</code> into 0.05 (5%).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>map_nc_constr <span class="ot">&lt;-</span> <span class="fu">set_pop_tol</span>(map_nc, <span class="fl">0.05</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">redist_smc</span>(map_nc_constr, <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>SEQUENTIAL MONTE CARLO
Sampling 10 2666-unit maps with 14 districts and population between 708387 and 782954.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>With plans resampled from weights
Plans matrix: int [1:2666, 1:11] 1 1 1 1 1 1 1 1 1 1 ...
# A tibble: 154 × 3
   draw    district total_pop
   &lt;fct&gt;      &lt;int&gt;     &lt;dbl&gt;
 1 cd_2020        1    745033
 2 cd_2020        2    744646
 3 cd_2020        3    747128
 4 cd_2020        4    745889
 5 cd_2020        5    745852
 6 cd_2020        6    745599
 7 cd_2020        7    746762
 8 cd_2020        8    745420
 9 cd_2020        9    747640
10 cd_2020       10    746272
# ℹ 144 more rows</code></pre>
</div>
</div>
<p>Now, as the population tolerance changes, the possible range of <code>total_pop</code> expanded between 708,387 and 782,954.</p>
</section>
<section id="administrative-boundary-splits" class="level4">
<h4 class="anchored" data-anchor-id="administrative-boundary-splits">Administrative Boundary Splits</h4>
<p>We can also add a soft constraints to the simulation. Here, we will try to add a constraint that prefers the fewer county splits by creating <code>redist_constr</code> object.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>constr <span class="ot">&lt;-</span> <span class="fu">redist_constr</span>(map_nc_constr)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>constr <span class="ot">&lt;-</span> <span class="fu">add_constr_splits</span>(constr, <span class="at">strength =</span> <span class="fl">1.5</span>, <span class="at">admin =</span> county)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>smc_plans_constr <span class="ot">&lt;-</span> <span class="fu">redist_smc</span>(</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">map =</span> map_nc,</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">nsims =</span> <span class="dv">500</span>,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">runs =</span> <span class="dv">4</span>L,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">constraints =</span> constr</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="redist_plans-output" class="level3">
<h3 class="anchored" data-anchor-id="redist_plans-output"><code>redist_plans</code> Output</h3>
<p>Changing the constraints means changing the output sample of the simulations. Although we are going to explain in detail how to evaluate and analyze the simulation output with certain measures, here let’s see how the constraints changed the population deviation of the simulation outcome.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># original constraints</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>smc_plans_basic <span class="sc">|&gt;</span> </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(draw) <span class="sc">|&gt;</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">pop_dev =</span> <span class="fu">max</span>(<span class="fu">abs</span>(total_pop <span class="sc">/</span> <span class="fu">mean</span>(total_pop) <span class="sc">-</span> <span class="dv">1</span>))) <span class="sc">|&gt;</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">redist.plot.hist</span>(pop_dev, <span class="at">bins =</span> <span class="dv">10</span>) <span class="sc">+</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlim</span>(<span class="fu">c</span>(<span class="fl">0.003</span>, <span class="fl">0.0055</span>)) <span class="sc">+</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>()</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="co"># customized constraints</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>smc_plans_constr <span class="sc">|&gt;</span> </span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(draw) <span class="sc">|&gt;</span></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">pop_dev =</span> <span class="fu">max</span>(<span class="fu">abs</span>(total_pop <span class="sc">/</span> <span class="fu">mean</span>(total_pop) <span class="sc">-</span> <span class="dv">1</span>))) <span class="sc">|&gt;</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">redist.plot.hist</span>(pop_dev, <span class="at">bins =</span> <span class="dv">10</span>) <span class="sc">+</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlim</span>(<span class="fu">c</span>(<span class="fl">0.003</span>, <span class="fl">0.0055</span>)) <span class="sc">+</span></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="redist101_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="redist101_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="north-carolina-analysis-example" class="level2">
<h2 class="anchored" data-anchor-id="north-carolina-analysis-example">North Carolina Analysis Example</h2>
<p>We will now demonstrate an example of redistricting analysis using the simulated plans from the 50-States Project.</p>
<section id="setup" class="level3">
<h3 class="anchored" data-anchor-id="setup">Setup</h3>
<p>First, we load the required packages for analysis. We also load the code for generating the validation plots, which will help us create visualizations for the summary statistics of the simulations.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">FALSE</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alarmdata)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(redist)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(geomander)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"fifty-states/validate.R"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="download-simulation-data" class="level3">
<h3 class="anchored" data-anchor-id="download-simulation-data">Download Simulation Data</h3>
<p>We can access data from all 50 states in the US using the <code>alarmdata</code> package. Here, we use North Carolina as an example: <code>alarm_census_vest()</code> downloads geographic, demographic, and election data, <code>alarm_50state_map()</code> loads the <code>redist_map</code> object that contains precinct geometries and adjacencies, and <code>alarm_50state_plans()</code> downloads the <code>redist_plans</code> object that contains 5000 pre-simulated redistricting plans from the <a href="https://doi.org/10.48550/arXiv.2206.10763">50-State Redistricting Simulations</a>.</p>
<p>The code for how these plans were generated is available on the <a href="https://github.com/alarm-redist/fifty-states/tree/main/analyses/NC_cd_2020">50-State GitHub repository</a>.</p>
<p>Specifically in North Carolina, districts must: 1) be contiguous 2) have equal populations 3) be geographically compact 4) preserve county boundaries as much as possible. Each of these redistricting requirements, in addition to compliance with the 1965 Voting Rights Act, were closely followed when conducting the simulations.</p>
</section>
<section id="visualization" class="level3">
<h3 class="anchored" data-anchor-id="visualization">Visualization</h3>
<p>We can plot some of the simulated plans to visualize the geographical boundaries of the simulated districts.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="redist101_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can also plot the VI distance of each plan, which measures how different the simulated plans are from one another. In the following plot, the VI distances are mostly within the range 0.5-1.0, which means that the simulated plans include a diverse set of geographical arrangements.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="redist101_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can also visualize the compactness of entire plans. The following plot shows the compactness of the simulated plans at the plan level, using the Fraction of Edges Kept measure. The compactness of the NC 2020 enacted plan is within the mid-upper range of the simulated plans, suggesting that the plans were constructed with appropriate compactness considerations.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="redist101_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The following plot displays the distribution of compactness across the simulated plans at the district level, using the Polsby-Popper compactness measure.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="redist101_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="simulation-evaluation" class="level3">
<h3 class="anchored" data-anchor-id="simulation-evaluation">Simulation Evaluation</h3>
<p>To evaluate the performance of the simulations, we can use <code>summary(plans)</code> to check for any bottlenecks or efficiency losses. Be sure to check that all R-hat values are below 1.05 and that the SMC runs have converged. For NC, 2 runs of 10,000 simulations is the typical size needed for convergence. Example summary statistics for fully converged simulation runs are pasted below.</p>
<pre><code>SMC: 20,000 sampled plans of 14 districts on 2,666 units
`adapt_k_thresh`=0.985 • `seq_alpha`=0.5
`est_label_mult`=1 • `pop_temper`=0.01

Plan diversity 80% range: 0.69 to 0.87

R-hat values for summary statistics:
pop_overlap      total_vap       plan_dev      comp_edge    comp_polsby       pop_hisp      pop_white      pop_black       pop_aian 
1.011740       1.004010       1.016022       1.006402       1.007232       1.011292       1.001015       1.008898       1.000115 
pop_asian       pop_nhpi      pop_other        pop_two       vap_hisp      vap_white      vap_black       vap_aian      vap_asian 
1.027659       1.001441       1.040853       1.000344       1.011211       1.001468       1.005998       1.000307       1.030569 
vap_nhpi      vap_other        vap_two pre_16_rep_tru pre_16_dem_cli uss_16_rep_bur uss_16_dem_ros gov_16_rep_mcc gov_16_dem_coo 
1.006742       1.039742       1.003739       1.014649       1.041666       1.011259       1.037633       1.011370       1.036032 
atg_16_rep_new atg_16_dem_ste sos_16_rep_lap sos_16_dem_mar pre_20_rep_tru pre_20_dem_bid uss_20_rep_til uss_20_dem_cun gov_20_rep_for 
1.012634       1.036626       1.010377       1.033683       1.012790       1.048726       1.009076       1.047310       1.013620 
gov_20_dem_coo atg_20_rep_one atg_20_dem_ste sos_20_rep_syk sos_20_dem_mar         arv_16         adv_16         arv_20         adv_20 
1.046216       1.009898       1.044914       1.009182       1.044455       1.010635       1.036324       1.010868       1.046275 
county_splits    muni_splits            ndv            nrv        ndshare          e_dvs         pr_dem          e_dem          pbias 
1.004991       1.014032       1.043048       1.012762       1.028974       1.028886       1.044242       1.006234       1.006050 
egap 
1.004837 

Sampling diagnostics for SMC run 1 of 2
Eff. samples (%) Acc. rate Log wgt. sd  Max. unique Est. k 
Split 1     8,041 (80.4%)     11.5%        0.43 6,354 (101%)     12 
Split 2     7,829 (78.3%)     17.7%        0.54 5,974 ( 95%)      7 
Split 3     7,698 (77.0%)     22.3%        0.61 5,852 ( 93%)      5 
Split 4     7,560 (75.6%)     31.0%        0.65 5,867 ( 93%)      3 
Split 5     7,423 (74.2%)     18.4%        0.68 5,671 ( 90%)      5 
Split 6     7,445 (74.5%)     20.7%        0.70 5,740 ( 91%)      4 
Split 7     7,552 (75.5%)     19.2%        0.72 5,709 ( 90%)      4 
Split 8     7,442 (74.4%)     23.1%        0.71 5,675 ( 90%)      3 
Split 9     7,390 (73.9%)     21.1%        0.73 5,696 ( 90%)      3 
Split 10    7,515 (75.2%)     14.3%        0.73 5,664 ( 90%)      4 
Split 11    7,669 (76.7%)     15.5%        0.72 5,482 ( 87%)      3 
Split 12    7,820 (78.2%)     11.8%        0.70 5,334 ( 84%)      3 
Split 13    7,423 (74.2%)      4.0%        0.77 4,850 ( 77%)      3 
Resample    2,891 (28.9%)       NA%        1.21 4,691 ( 74%)     NA 

Sampling diagnostics for SMC run 2 of 2
Eff. samples (%) Acc. rate Log wgt. sd  Max. unique Est. k 
Split 1     8,087 (80.9%)     15.5%        0.43 6,267 ( 99%)      9 
Split 2     7,872 (78.7%)     20.2%        0.54 5,938 ( 94%)      6 
Split 3     7,650 (76.5%)     21.9%        0.60 5,908 ( 93%)      5 
Split 4     7,565 (75.7%)     24.5%        0.65 5,812 ( 92%)      4 
Split 5     7,380 (73.8%)     18.5%        0.68 5,786 ( 92%)      5 
Split 6     7,431 (74.3%)     27.1%        0.71 5,693 ( 90%)      3 
Split 7     7,455 (74.6%)     19.4%        0.73 5,683 ( 90%)      4 
Split 8     7,509 (75.1%)     23.0%        0.73 5,720 ( 90%)      3 
Split 9     7,523 (75.2%)     12.8%        0.71 5,734 ( 91%)      5 
Split 10    7,509 (75.1%)     13.9%        0.70 5,664 ( 90%)      4 
Split 11    7,403 (74.0%)      9.4%        0.74 5,542 ( 88%)      5 
Split 12    7,589 (75.9%)     11.9%        0.73 5,351 ( 85%)      3 
Split 13    7,744 (77.4%)      4.1%        0.72 4,926 ( 78%)      3 
Resample    3,593 (35.9%)       NA%        1.15 4,889 ( 77%)     NA</code></pre>
<p>We can also run <code>validate_analysis(plans, map)</code> to generate a set of useful simulation visualizations.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="redist101_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="comparing-custom-plans" class="level3">
<h3 class="anchored" data-anchor-id="comparing-custom-plans">Comparing Custom Plans</h3>
<p>The 50-State <code>redist_plans</code> objects include data for the 2020 enacted districting plans. However, analysts might want to compare other custom plans to the 50-State simulations. This can be done with <code>alarm_add_plan()</code>. The following example adds one of the previously proposed 2020 congressional maps for North Carolina as a reference plan to the <code>plans_nc</code> object. Many submitted maps are publicly available online on sites such as <a href="https://redistrictingdatahub.org/data/download-data/#state-menu">Redistricting Data Hub</a>, <a href="https://redistricting.lls.edu/mapdownload/">All About Redistricting</a>, or state government websites. The North Carolina enacted and proposed maps came from the <a href="https://www.ncleg.gov/Redistricting">North Carolina General Assembly</a>.</p>
<p>After the old reference plan has been added, we can compare the simulation statistics to both the previously proposed plan, labeled <code>cd_2020_ex</code>, and the currently enacted plan, labeled <code>cd_2020</code>. The following code plots the number of county splits, and we can see that the current plan actually splits more counties than the previous plan.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="redist101_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can compare distributions of different summary statistics across districts. The following boxplots display the distribution of Democratic vote percentage across each district. This plot shows that there are more majority-Democratic districts in the current plan than in the previously ratified plan, due to less packing of voters.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="redist101_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Similarly, we can visualize the minority voting age population (VAP) percentage in each district. This plot shows that voters are less packed in the highest MVAP districts, leading to more opportunity districts.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="redist101_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Overall, although the newly enacted plan split more counties than the previously proposed plan, the partisan and demographic metrics of the current plan are not among the far outliers of the simulation diagnostics, suggesting that the current plan is a more representative configuration given the specific redistricting requirements in North Carolina.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/alarm-redist\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© Copyright 2021 the <a href="about.html">ALARM Project</a>. <br>Software licensed under the <a href="https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html">GNU Public License, v2.0</a>.</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>