---
title: "Revised: Impact of the Census Disclosure Avoidance System"
description: |
    We are releasing an updated version of our analysis of the U.S. Census'
    privacy protection system and its impacts on the redistricting process.
author:
    - name: Christopher T. Kenny
      affiliation: Department of Government, Harvard University
      location: Cambridge, MA
      email: christopherkenny@fas.harvard.edu
    - name: Shiro Kuriwaki
      affiliation: Department of Government, Harvard University
      location: Cambridge, MA
      email: kuriwaki@g.harvard.edu
    - name: Cory McCartan
      affiliation: Department of Statistics, Harvard University
      location: Cambridge, MA
      email: cmccartan@fas.harvard.edu
    - name: Evan Rosenman
      affiliation: Harvard Data Science Initiative
      location: Cambridge, MA
      email: erosenm@fas.harvard.edu
    - name: Tyler Simko
      affiliation: Department of Government, Harvard University
      location: Cambridge, MA
      email: tsimko@g.harvard.edu
    - name: Kosuke Imai
      affiliation: Departments of Government and Statistics, Harvard University
      location: Cambridge, MA
      email: imai@harvard.edu
date: July 5, 2021
output:
  distill::distill_article:
    self_contained: false
citation: false
---

Last month, the ALARM Project released a report examining "The Impact U.S.
Census Disclosure Avoidance System on Redistricting and Voting Rights Analysis."
We thank everyone who provided us with feedback on this first version, which was
written as a comment on the April 28, 2021 Demonstration Data. The Census Bureau
has since updated the system parameters, and as such, we are releasing an
updated version.

**Revised report: [*The Impact of the U.S. Census Disclosure Avoidance System on
Redistricting and Voting Rights
Analysis*](https://arxiv.org/pdf/2105.14197.pdf)**

Notably, we expand our study of bias related to racial heterogeneity to include
four new states of interest: Alabama, Delaware, Utah, and Washington. We also
expand our studies of partisan and racial effects in redistricting to include
more cases and provide additional information on the ranges of possible
outcomes. These changes come alongside a restructuring of the paper and several
smaller edits to recognize additional work focused on the new DAS methodologies
used this year by the Census Bureau.With this version, we are also releasing
replication data and code, available on the [Harvard
Dataverse](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/TNNSXG).
